language: java

sudo: false
dist: trusty

script: ant jar

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $YOUR_USER_NAME
  - THETAG="$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - echo $THETAG
  - git tag $THETAG

deploy:
  provider: releases
  api_key: 
    secure: $keymeme
  file: "adbcontrol.jar"
  skip_cleanup: true
    on:
    tags: true
  
